package install

import (
	"strings"

	"github.com/renderorange/knowledge-mcp/tools"
)

const (
	agentsStartMark = "<!-- knowledge-mcp:start -->"
	agentsEndMark   = "<!-- knowledge-mcp:end -->"
)

// UpsertBlock replaces the marker-delimited region of content (markers
// inclusive) when present, otherwise appends the block at the end.
func UpsertBlock(existing, block []byte, startMark, endMark string) []byte {
	content := string(existing)
	start := strings.Index(content, startMark)
	end := strings.Index(content, endMark)
	if start >= 0 && end > start {
		endLine := strings.Index(content[end:], "\n")
		if endLine < 0 {
			endLine = len(content) - end
		}
		head := content[:start]
		tail := content[end+endLine:]
		if strings.HasSuffix(head, "\n\n") {
			head = strings.TrimRight(head, "\n") + "\n\n"
		}
		return []byte(head + string(block) + tail)
	}
	sep := "\n"
	trimmed := strings.TrimRight(content, "\n")
	if trimmed != "" && !strings.HasSuffix(trimmed, "\n\n") {
		sep = "\n\n"
	}
	return []byte(trimmed + sep + string(block) + "\n")
}

// RenderAgentsBlock renders the minimal always-loaded instruction block.
func RenderAgentsBlock(registry []tools.ToolSpec) []byte {
	var rows strings.Builder
	for _, spec := range registry {
		rows.WriteString("| `" + spec.Name + "` | " + spec.Purpose + " |\n")
	}
	block := agentsStartMark + "\n" +
		"## Persistent Knowledge Store (knowledge-mcp)\n" +
		"\n" +
		"Projects keep distilled knowledge (conventions, subsystem notes, decisions) in\n" +
		".agents/ stores queried through MCP tools. The store is the source of truth;\n" +
		"this block is regenerated by `knowledge-mcp install`.\n" +
		"\n" +
		"### Tool use\n" +
		"\n" +
		"| Tool | When |\n" +
		"|---|---|\n" +
		rows.String() +
		"### Hard rules\n" +
		"\n" +
		"- **Summaries are not rules.** list_knowledge summaries OMIT enforcement\n" +
		"  details. Before acting in a domain, run query_knowledge and read the FULL\n" +
		"  detail of matching entries.\n" +
		"- **No duplication.** Never store rules that already live in an always-loaded\n" +
		"  instructions file; never copy AGENTS.md rules into entries intentlessly.\n" +
		"- **Detail is a distilled summary** (10-20 lines of query-able facts), never\n" +
		"  a copy of source files.\n" +
		"- **Provenance.** Every entry records where it was learned (source field).\n" +
		agentsEndMark + "\n"
	return []byte(block)
}
