package install

// RenderPlugin renders the opencode augment plugin (tool.execute.after on
// Grep/Glob). It is a full-file artifact: overwritten on reinstall.
func RenderPlugin(binPath string) []byte {
	src := "// knowledge-mcp:start\n" +
		"// Generated by knowledge-mcp install. Overwritten on reinstall;\n" +
		"// this file is fully generated.\n" +
		"import { spawn } from 'node:child_process';\n" +
		"\n" +
		"const BIN = '" + binPath + "';\n" +
		"\n" +
		"function augment(tool, args) {\n" +
		"  return new Promise((resolve) => {\n" +
		"    let done = false;\n" +
		"    const finish = (out) => { if (!done) { done = true; resolve(out); } };\n" +
		"    let child;\n" +
		"    try {\n" +
		"      child = spawn(BIN, ['hook-augment'], {\n" +
		"        stdio: ['pipe', 'pipe', 'ignore'],\n" +
		"        env: { ...process.env, KNM_LOG_LEVEL: 'error' },\n" +
		"      });\n" +
		"    } catch (err) {\n" +
		"      return finish('');\n" +
		"    }\n" +
		"    const timer = setTimeout(() => { try { child.kill(); } catch (err) {} finish(''); }, 3000);\n" +
		"    let out = '';\n" +
		"    child.stdout.on('data', (d) => (out += d.toString()));\n" +
		"    child.on('error', () => finish(''));\n" +
		"    child.on('close', () => { clearTimeout(timer); finish(out); });\n" +
		"    child.stdin.on('error', () => finish(''));\n" +
		"    child.stdin.end(JSON.stringify({\n" +
		"      hook_event_name: 'PostToolUse',\n" +
		"      tool_name: tool,\n" +
		"      tool_input: args ?? {},\n" +
		"    }));\n" +
		"  });\n" +
		"}\n" +
		"\n" +
		"export const KnowledgeMcp = async ({ client }) => ({\n" +
		"  'session.created': async () => {\n" +
		"    client.tui.showToast({ body: { message: 'knowledge-mcp: if tools are missing, check external_directory permission in opencode config', variant: 'info' } });\n" +
		"  },\n" +
		"  'tool.execute.after': async (input, output) => {\n" +
		"    const tool = input?.tool === 'grep' ? 'Grep' : input?.tool === 'glob' ? 'Glob' : null;\n" +
		"    if (!tool) return;\n" +
		"    const extra = await augment(tool, output?.args);\n" +
		"    if (extra && typeof output?.output === 'string') {\n" +
		"      output.output += '\\n' + extra;\n" +
		"    }\n" +
		"  },\n" +
		"});\n" +
		"// knowledge-mcp:end\n"
	return []byte(src)
}
